version: "3.7"

services:
  web:
    env_file:
      - .env
    build: .
    volumes:
      - .:/simple_activities:cached
      - bundle_cache:/bundle_cache
    ports:
      - 3000:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:14.1-alpine
    volumes:
      - pg_data:/var/lib/postgresql/data/pgdata
    ports:
      - 5435:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata

volumes:
  bundle_cache:
  pg_data:
