default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: simple_analytics_development

staging:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

production:
  <<: *default
  database: <%= ENV.fetch("DB_NAME", "postgres") %>
  port: <%= ENV.fetch("DB_PORT", "5432") %>

test:
  <<: *default
  database: simple_analytics_test
